# Generated by Django 5.1.4 on 2025-03-17 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0002_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='date_a_soumettre',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
