# Generated by Django 5.1.4 on 2025-03-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0003_exercice_date_a_soumettre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercice',
            old_name='classe_affected',
            new_name='classes_affected',
        ),
    ]
