# Generated by Django 5.1.4 on 2025-03-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0004_rename_classe_affected_exercice_classes_affected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='date_a_soumettre',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='fichier',
            field=models.FileField(default='', upload_to='exercices/'),
            preserve_default=False,
        ),
    ]
