# Generated by Django 5.1.4 on 2025-03-24 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0005_alter_exercice_date_a_soumettre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_attrib', to='exercices.solution')),
            ],
        ),
    ]
