# Generated by Django 5.1.4 on 2025-03-27 20:25

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0006_solution_note_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='fichier',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='exercices/', verbose_name='Fichier S3'),
        ),
    ]
