version: '3.8'

services:
  backend:
    build: ./projetsql
    env_file: ./projetsql/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./vue-project
    ports:
      - "5173:5173"
    restart: unless-stopped

  db:
    image: mysql:8.0
    env_file: ./projetsql/.env
    environment:
      MYSQL_DATABASE: ExerciceIODB
      MYSQL_USER: devgit
      MYSQL_PASSWORD: passer
      MYSQL_ROOT_PASSWORD: passer
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_data: