# Generated by Django 5.1.4 on 2025-03-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('professeur', 'Professeur'), ('etudiant', 'Etudiant')], default='etudiant', max_length=10),
        ),
    ]
