# Generated by Django 5.1.4 on 2025-03-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='professeurs', to='utilisateurs.classe'),
        ),
    ]
