# Generated by Django 5.1.4 on 2025-03-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_utilisateur_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='classes',
            new_name='classes_affected',
        ),
    ]
