# Generated by Django 5.1.4 on 2025-03-22 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_rename_classes_utilisateur_classes_affected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.classe'),
        ),
    ]
