# Generated by Django 5.1.4 on 2025-03-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercices', '0006_solution_note_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(choices=[('DEEPSEEK', 'DeepSeek'), ('OLLAMA', 'Ollama')], max_length=20)),
                ('raw_response', models.JSONField()),
                ('feedback', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='exercices.solution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
