# Generated by Django 5.1.4 on 2025-03-30 23:05

import corrections.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0002_alter_correction_options_remove_correction_feedback_and_more'),
        ('exercices', '0008_alter_solution_fichier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correction',
            options={'verbose_name': 'Correction', 'verbose_name_plural': 'Corrections'},
        ),
        migrations.RemoveIndex(
            model_name='correction',
            name='corrections_exercic_d124f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='correction',
            name='corrections_score_071616_idx',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='created_at',
            new_name='date_correction',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='annotated_document',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='corrected_by',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='exercice',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='raw_response',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='score',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='structured_feedback',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='correction',
            name='annotated_file',
            field=models.FileField(blank=True, null=True, storage=corrections.models.CorrectionFileStorage(), upload_to='%Y/%m/%d', verbose_name='Document annoté (S3)'),
        ),
        migrations.AddField(
            model_name='correction',
            name='commentaires',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='correction',
            name='corrige_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='correction',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='provider',
            field=models.CharField(choices=[('DEEPSEEK', 'DeepSeek'), ('MANUAL', 'Manuelle')], default='DEEPSEEK', max_length=20),
        ),
        migrations.AlterField(
            model_name='correction',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction_rel', to='exercices.solution'),
        ),
    ]
